name: CloudStream Derleyici

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout builds branch
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x src/gradlew || true

      - name: Build plugins
        working-directory: src
        run: ./gradlew clean createCs3 makePluginsJson --no-daemon

      - name: Copy outputs
        run: |
          mkdir -p builds
          cp src/build/outputs/*.cs3 builds/ || true
          cp src/build/outputs/plugins.json builds/ || true

      - name: Replace author tag
        run: |
          if [ -f "builds/plugins.json" ]; then
            sed -i 's/@KekikAkademi/@UmayTrade/g' builds/plugins.json || true
          fi

      - name: Push to builds branch
        run: |
          cd builds
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "Yeni derleme: $GITHUB_SHA" || echo "No changes"
          git push origin HEAD:builds
