name: CloudStream Derleyici

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source (master)
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout builds branch
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Ensure gradlew is executable
        run: |
          cd src
          chmod +x gradlew || true

      - name: Build plugin and create .cs3 and plugins.json
        working-directory: src
        run: |
          ./gradlew clean createCs3 makePluginsJson --no-daemon
          # outputs: src/build/outputs/*.cs3, src/build/outputs/plugins.json

      - name: Copy outputs to builds workspace
        run: |
          mkdir -p $GITHUB_WORKSPACE/builds
          cp src/build/outputs/*.cs3 $GITHUB_WORKSPACE/builds/ || true
          cp src/build/outputs/plugins.json $GITHUB_WORKSPACE/builds/ || true

      - name: Replace author tag in plugins.json
        run: |
          if [ -f "$GITHUB_WORKSPACE/builds/plugins.json" ]; then
            sed -i 's/@KekikAkademi/@UmayTrade/g' $GITHUB_WORKSPACE/builds/plugins.json || true
          fi

      - name: Commit and push to builds branch
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: actions@github.com
        run: |
          cd $GITHUB_WORKSPACE/builds
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin builds || true
          git checkout -B builds
          git config user.email "$GIT_AUTHOR_EMAIL"
          git config user.name "$GIT_AUTHOR_NAME"
          git add .
          git commit -m "Automatik derleme: $GITHUB_SHA" || echo "No changes to commit"
          git push --force origin builds
